export enum NotificationType {
  API_EVENT_TYPE_UNSPECIFIED = 'API_EVENT_TYPE_UNSPECIFIED',
  API_EVENT_TYPE_CONCURRENT_LOGIN = 'API_EVENT_TYPE_CONCURRENT_LOGIN',
  API_EVENT_TYPE_RUN_LIST_UPDATED = 'API_EVENT_TYPE_RUN_LIST_UPDATED',
}
