export enum RunStatus {
  LOADER_RUN_CHANGE_TYPE_UNSPECIFIED = 'LOADER_RUN_CHANGE_TYPE_UNSPECIFIED',
  LOADER_RUN_CHANGE_TYPE_RUN_CREATED = 'LOADER_RUN_CHANGE_TYPE_RUN_CREATED',
  LOADER_RUN_CHANGE_TYPE_RUN_MODIFIED = 'LOADER_RUN_CHANGE_TYPE_RUN_MODIFIED',
  LOADER_RUN_CHANGE_TYPE_RUN_REMOVED = 'LOADER_RUN_CHANGE_TYPE_RUN_REMOVED',
}
